'use client';
import {useEffect,useState} from 'react';
import {AdminPagination} from './admin-ui';
import {activityModules} from '@/lib/staff-activity.mjs';
import {actionLabels} from '@/lib/list-domain.mjs';
const extra:any={'group-save':'保存权限组','member-assign':'分配权限组','account-save':'更新子账号','staff-login':'管理员登录','staff-change-password':'修改管理员密码','legacy-marketing':'修改历史营销授权','permission-legacy-orders':'修改历史订单授权'};
export default function StaffActivity({initialActor=''}:{initialActor?:string}) {
  const [filter,setFilter]=useState({actor:initialActor,module:'',action:'',from:'',to:''}),[query,setQuery]=useState({...filter,page:1}),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  useEffect(()=>{let live=true;setLoading(true);setError('');fetch('/api/staff/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(query)}).then(async response=>{const value:any=await response.json();if(!response.ok)throw Error(value.error||'日志加载失败');if(live)setResult(value);}).catch(e=>{if(live){setResult(null);setError(e.message);}}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[query]);
  return <section><h2>操作日志</h2><form className="admin-filter-bar" onSubmit={e=>{e.preventDefault();setQuery({...filter,page:1});}}><label>账号（操作者或被修改账号）<input value={filter.actor} maxLength={254} onChange={e=>setFilter({...filter,actor:e.target.value})}/></label><label>模块<select value={filter.module} onChange={e=>setFilter({...filter,module:e.target.value})}><option value="">全部模块</option>{Object.entries(activityModules).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><label>操作<input list="account-log-actions" value={filter.action} maxLength={80} placeholder="选择或填写操作标识" onChange={e=>setFilter({...filter,action:e.target.value})}/><datalist id="account-log-actions">{Object.entries({...actionLabels,...extra}).map(([key,value]:any)=><option key={key} value={key}>{value}</option>)}</datalist></label>{[['from','开始日期（UTC）'],['to','结束日期（UTC）']].map(([key,label])=><label key={key}>{label}<input type="date" value={(filter as any)[key]} onChange={e=>setFilter({...filter,[key]:e.target.value})}/></label>)}<button aria-busy={Boolean(loading)} className="btn primary" disabled={loading}>筛选</button><button type="button" className="btn" onClick={()=>{const empty={actor:'',module:'',action:'',from:'',to:''};setFilter(empty);setQuery({...empty,page:1});}}>重置</button></form>
    <p className="muted">日志只读。新授权及子账号变更展示前后值；旧记录没有结果字段时标为“已记录”，不推定成功。历史失败事件未必完整；不展示密钥、密码或原始请求。</p>
    {error&&<p className="error" role="alert">{error}<button className="btn" onClick={()=>setQuery({...query})}>重试</button></p>}{loading&&<p role="status">正在加载日志…</p>}
    {result&&<><div className="panel account-table"><table className="list-table"><thead><tr>{['时间','操作者','模块 / 操作','对象','结果','关键变更'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{result.rows.map((row:any)=><tr key={row.id}><td>{new Date(row.created).toLocaleString('zh-CN')}</td><td><button className="account-link" onClick={()=>{setFilter({...filter,actor:row.actor});setQuery({...filter,actor:row.actor,page:1});}}>{row.actor||'未记录'}</button></td><td>{(activityModules as any)[row.module]||row.module}<small>{extra[row.action]||(actionLabels as any)[row.action]||row.action}</small></td><td>{row.target||'未记录'}</td><td>{row.result==='success'?'成功':'已记录'}</td><td>{Object.keys(row.before||{}).length||Object.keys(row.after||{}).length?<details><summary>查看变更</summary><p>变更前</p><pre>{JSON.stringify(row.before,null,2)}</pre><p>变更后</p><pre>{JSON.stringify(row.after,null,2)}</pre></details>:'历史记录未保存变更详情'}</td></tr>)}{!result.rows.length&&<tr><td colSpan={6}>当前筛选条件下暂无日志</td></tr>}</tbody></table></div><AdminPagination page={query.page} pages={Math.min(150,Math.max(1,Math.ceil(result.total/result.size)))} total={result.total} busy={loading} onPage={page=>setQuery({...query,page})}>{query.page>=150&&<span>请缩小日期或账号范围查看更早记录</span>}</AdminPagination></>}
  </section>;
}
