CREATE TABLE `order_counters` (
	`day` text PRIMARY KEY NOT NULL,
	`sequence` integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE `orders` ADD `order_number` text;--> statement-breakpoint
CREATE UNIQUE INDEX `orders_number` ON `orders` (`order_number`);
--> statement-breakpoint
WITH numbered AS (SELECT id, CASE WHEN sandbox=1 THEN 'TEST-' ELSE '' END || strftime('%Y%m%d%H%M%S',created_at,'+8 hours') || '-' || CASE WHEN upper(trim(json_extract(data,'$.address.country'))) IN ('AD','AE','AF','AG','AI','AL','AM','AO','AQ','AR','AS','AT','AU','AW','AX','AZ','BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV','BW','BY','BZ','CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CU','CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ET','FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP','GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN','IO','IQ','IR','IS','IT','JE','JM','JO','JP','KE','KG','KH','KI','KM','KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MF','MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ','NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','PA','PE','PF','PG','PH','PK','PL','PM','PN','PR','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY','SZ','TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA','UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','YE','YT','ZA','ZM','ZW') THEN upper(trim(json_extract(data,'$.address.country'))) WHEN json_extract(data,'$.address.country') IN ('中国','China','中国大陆') THEN 'CN' ELSE 'ZZ' END || '-' || printf('%06d',row_number() OVER (PARTITION BY strftime('%Y%m%d',created_at,'+8 hours') ORDER BY created_at,id)) AS number FROM orders) UPDATE orders SET order_number=(SELECT number FROM numbered WHERE numbered.id=orders.id);
--> statement-breakpoint
INSERT INTO order_counters SELECT strftime('%Y%m%d',created_at,'+8 hours'),count(*) FROM orders GROUP BY strftime('%Y%m%d',created_at,'+8 hours');
--> statement-breakpoint
CREATE TRIGGER order_number_input BEFORE INSERT ON orders BEGIN SELECT CASE WHEN NEW.order_number IS NOT NULL OR strftime('%Y%m%d',NEW.created_at,'+8 hours') IS NULL THEN RAISE(ABORT,'订单编号由系统生成，创建时间必须有效') END; END;
--> statement-breakpoint
CREATE TRIGGER order_number_assign AFTER INSERT ON orders BEGIN INSERT INTO order_counters(day,sequence) VALUES(strftime('%Y%m%d',NEW.created_at,'+8 hours'),1) ON CONFLICT(day) DO UPDATE SET sequence=sequence+1; UPDATE orders SET order_number=CASE WHEN sandbox=1 THEN 'TEST-' ELSE '' END || strftime('%Y%m%d%H%M%S',created_at,'+8 hours') || '-' || CASE WHEN upper(trim(json_extract(data,'$.address.country'))) IN ('AD','AE','AF','AG','AI','AL','AM','AO','AQ','AR','AS','AT','AU','AW','AX','AZ','BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV','BW','BY','BZ','CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CU','CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ET','FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP','GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN','IO','IQ','IR','IS','IT','JE','JM','JO','JP','KE','KG','KH','KI','KM','KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MF','MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ','NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','PA','PE','PF','PG','PH','PK','PL','PM','PN','PR','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY','SZ','TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA','UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','YE','YT','ZA','ZM','ZW') THEN upper(trim(json_extract(data,'$.address.country'))) WHEN json_extract(data,'$.address.country') IN ('中国','China','中国大陆') THEN 'CN' ELSE 'ZZ' END || '-' || printf('%06d',(SELECT sequence FROM order_counters WHERE day=strftime('%Y%m%d',NEW.created_at,'+8 hours'))) WHERE id=NEW.id; END;
--> statement-breakpoint
CREATE TRIGGER order_number_immutable BEFORE UPDATE OF order_number ON orders WHEN OLD.order_number IS NOT NULL AND NEW.order_number IS NOT OLD.order_number BEGIN SELECT RAISE(ABORT,'订单编号不可修改'); END;
