import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
function setup(){const db=new DatabaseSync(':memory:');db.exec("PRAGMA foreign_keys=ON;CREATE TABLE contents(id TEXT PRIMARY KEY,kind TEXT,status TEXT,data TEXT,updated_at TEXT);CREATE TABLE assets(id TEXT PRIMARY KEY);CREATE TABLE settings(id TEXT PRIMARY KEY,data TEXT)");db.exec(readFileSync(new URL('../drizzle/0008_sloppy_annihilus.sql',import.meta.url),'utf8'));db.prepare('INSERT INTO contents VALUES(?,?,?,?,?)').run('p','products','published',JSON.stringify({trade:{currency:'CNY',inventory:3,variants:[{key:'a',enabled:true,priceMinor:100},{key:'b',enabled:true,priceMinor:100}]}}),'old');return db}
function create(db,id,quantity,variant='a'){db.exec('BEGIN');try{db.prepare('INSERT INTO orders(id,user_id,request_key,status,currency,subtotal,shipping,total,data,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,'u',id,'building','CNY',quantity*100,0,quantity*100,'{}','future','now','now');db.prepare('INSERT INTO order_items VALUES(?,?,?,?,?,?,?)').run(id,id,'p',variant,quantity,100,'{}');db.prepare("UPDATE orders SET status='pending_payment' WHERE id=?").run(id);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
test('shared stock locked across specs; failed order rolls back',()=>{const db=setup();create(db,'one',2);assert.throws(()=>create(db,'two',2,'b'));assert.equal(db.prepare('SELECT count(*) n FROM orders').get().n,1);create(db,'three',1,'b');assert.throws(()=>db.prepare("UPDATE contents SET data=json_set(data,'$.trade.inventory',2)").run());db.close()});
test('confirm payment deducts once; closing unpaid releases; refund does not restore until explicit',()=>{const db=setup();create(db,'one',2);db.exec("UPDATE orders SET status='pending_review' WHERE id='one';UPDATE orders SET status='pending_ship',paid=1 WHERE id='one'");assert.equal(JSON.parse(db.prepare('SELECT data FROM contents').get().data).trade.inventory,1);assert.throws(()=>db.exec("UPDATE orders SET paid=0 WHERE id='one'"));create(db,'two',1);db.exec("UPDATE orders SET status='closed' WHERE id='two'");create(db,'three',1);db.exec("UPDATE orders SET status='aftersale' WHERE id='one';UPDATE orders SET status='closed',refunded=1 WHERE id='one'");assert.equal(JSON.parse(db.prepare('SELECT data FROM contents').get().data).trade.inventory,1);db.exec("UPDATE orders SET restocked=1 WHERE id='one'");assert.equal(JSON.parse(db.prepare('SELECT data FROM contents').get().data).trade.inventory,3);assert.throws(()=>db.exec("UPDATE orders SET restocked=0 WHERE id='one'"));db.close()});
function redemptionSetup(){const db=setup();db.exec(readFileSync(new URL('../drizzle/0011_points_redemption.sql',import.meta.url),'utf8'));db.exec("UPDATE contents SET data=json_set(data,'$.trade.redemptionEnabled',json('true'),'$.trade.redemptionQuota',2,'$.trade.redemptionLimit',1,'$.trade.variants[0].pointsPrice',25)");return db}
function redeem(db,id,user='u',qty=1,price=25){db.exec('BEGIN');try{db.prepare('INSERT INTO orders(id,user_id,request_key,status,currency,subtotal,shipping,total,data,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,user,id,'building','PTS',qty*price,0,qty*price,'{"orderType":"points"}','future','now','now');db.prepare('INSERT INTO order_items VALUES(?,?,?,?,?,?,?)').run(id,id,'p','a',qty,price,'{}');db.prepare("UPDATE orders SET status='pending_payment' WHERE id=?").run(id);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
test('redemption validates points price, global quota and per-user quota',()=>{const db=redemptionSetup();assert.throws(()=>redeem(db,'bad','u',1,1));redeem(db,'one');assert.throws(()=>redeem(db,'two'));redeem(db,'three','v');assert.throws(()=>redeem(db,'four','w'));assert.equal(db.prepare('SELECT count(*) n FROM orders').get().n,2);db.close()});
test('cash and points reservations share stock; cancellation restores once and releases quota',()=>{const db=redemptionSetup();create(db,'cash',2);redeem(db,'one');assert.throws(()=>redeem(db,'over','v'));db.exec("UPDATE orders SET status='pending_review' WHERE id='one';UPDATE orders SET status='pending_ship',paid=1 WHERE id='one'");assert.equal(JSON.parse(db.prepare('SELECT data FROM contents').get().data).trade.inventory,2);db.exec("UPDATE orders SET status='aftersale' WHERE id='one';UPDATE orders SET status='closed',refunded=1 WHERE id='one';UPDATE orders SET restocked=1 WHERE id='one'");redeem(db,'again');assert.equal(JSON.parse(db.prepare('SELECT data FROM contents').get().data).trade.inventory,3);db.close()});

test('variant stock isolates reservations, deducts payment and restores explicitly',()=>{
 const db=redemptionSetup(); db.exec(readFileSync(new URL('../drizzle/0013_variant_inventory.sql',import.meta.url),'utf8'));
 db.exec("UPDATE contents SET data=json_set(data,'$.trade.inventoryMode','variants','$.trade.variants[0].inventory',1,'$.trade.variants[1].inventory',2)");
 create(db,'a',1); assert.throws(()=>create(db,'over',1),/规格库存/); create(db,'b',2,'b');
 assert.throws(()=>db.exec("UPDATE contents SET data=json_set(data,'$.trade.variants[0].inventory',0)"),/规格库存/);
 db.exec("UPDATE orders SET status='pending_review' WHERE id='a'; UPDATE orders SET status='pending_ship',paid=1 WHERE id='a'");
 assert.throws(()=>db.exec("UPDATE contents SET data=json_remove(data,'$.trade.variants[0]')"),/规格/);
 let t=JSON.parse(db.prepare('SELECT data FROM contents').get().data).trade; assert.equal(t.variants[0].inventory,0); assert.equal(t.variants[1].inventory,2); assert.equal(t.inventory,2);
 db.exec("UPDATE orders SET status='aftersale' WHERE id='a'; UPDATE orders SET status='closed',refunded=1 WHERE id='a'; UPDATE orders SET restocked=1 WHERE id='a'");
 t=JSON.parse(db.prepare('SELECT data FROM contents').get().data).trade; assert.equal(t.variants[0].inventory,1); assert.equal(t.inventory,3); db.close();
});
