export const SOFTWARE_NAME = 'GEO Studio';
export const SOFTWARE_VERSION = 'V2.8.4';
export const SOFTWARE_VERSION_DATE = '2026-09-23';
export const SOFTWARE_VERSION_LABEL = `${SOFTWARE_NAME} ${SOFTWARE_VERSION}`;
export const SOFTWARE_VERSION_DETAIL = `${SOFTWARE_VERSION} · ${SOFTWARE_VERSION_DATE}`;
