import {ActionButton,ActionText,ActionView,ActionInput} from '../../components/interaction';
import LoadingState from '../../components/loading-state';
import {latestRequest} from '../../lib/latest-request.mjs';
import {behavior,choiceKey} from '../../lib/behavior';
import {playbackCounter} from '../../../../lib/behavior-client.mjs';
import {useRef,useState} from 'react';
import Taro,{useLoad,useDidShow,useDidHide,useUnload,useShareAppMessage} from '@tarojs/taro';
import {View,Text,Image,Input,Button,Video} from '@tarojs/components';
import {request,image,origin,token} from '../../lib/api';
import RichBody from '../../components/rich-body';
import GlobalNavigation from '../../components/global-navigation';
import MediaInteractions from '../../components/media-interactions';
import './index.scss';
const api='/api/mini/media?kind=videos&action=';
export default function Videos(){
 const loads=useRef(latestRequest());useUnload(()=>loads.current.cancel());
 const [id,setId]=useState(''),[detail,setDetail]=useState<any>(),[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[type,setType]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(1),[error,setError]=useState(''),[loading,setLoading]=useState(true),[episode,setEpisode]=useState<any>(),[play,setPlay]=useState<any>(),[full,setFull]=useState(false);
 const metrics=useRef(playbackCounter());
 const browser=useRef(''),playback=useRef<any>(),last=useRef(0),pending=useRef<any>(),requestId=useRef(0);
 useLoad(params=>{const value=params.id||'';setId(value);void load(value,'','',1);const stored=Taro.getStorageSync('mini-video-browser');browser.current=typeof stored==='string'&&/^[\w-]{43}$/.test(stored)?stored:Array.from({length:43},()=> 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-'[Math.floor(Math.random()*64)]).join('');Taro.setStorageSync('mini-video-browser',browser.current)});
 useDidShow(()=>{if(pending.current&&token()){const ep=pending.current;pending.current=null;void start(ep)}});
 async function release(){const old=playback.current;playback.current=null;if(old&&old.session===token())try{await request(api+'release',{token:old.token,browser:browser.current})}catch{}}
 useDidHide(()=>{requestId.current++;void release();setPlay(undefined)});useUnload(()=>{requestId.current++;void release()});
 useShareAppMessage(()=>({title:detail?.series.titleZh||'视频',path:'/pages/videos/index'+(id?'?id='+id:'')}));
 async function load(value=id,search=q,category=type,n=page){const version=loads.current.begin();setLoading(true);setError('');try{const result=await request(api+(value?'detail&id='+value:'list&q='+encodeURIComponent(search)+'&type='+category+'&page='+n));if(!loads.current.isCurrent(version))return;if(value)setDetail(result);else{setRows(result.rows);setPage(result.page);setPages(result.pages)}}catch(e){if(loads.current.isCurrent(version))setError((e as Error).message)}finally{if(loads.current.isCurrent(version))setLoading(false)}}
 async function start(ep:any){if(!ep.preview&&!token()){pending.current=ep;await Taro.navigateTo({url:'/pages/login/index'});return;}const session=token();const version=++requestId.current;setError('');await release();if(session!==token())return;setEpisode(ep);metrics.current=playbackCounter();setPlay(undefined);try{const result=await request(api+'authorize',{id:ep.id,browser:browser.current},session);if(version!==requestId.current||session!==token()){if(session===token())await request(api+'release',{token:result.token,browser:browser.current});return;}playback.current={...result,session};setPlay(result);last.current=0;}catch(e){setError((e as Error).message)}}
 async function progress(position:number,force=false){const current=playback.current;if(!current||current.session!==token()||(!force&&Date.now()-last.current<10000))return;last.current=Date.now();try{await request(api+'progress',{token:current.token,browser:browser.current,position},current.session);if(current.session===token()&&Date.now()-(current.renewed||0)>600000){await request(api+'renew',{token:current.token,browser:browser.current},current.session);current.renewed=Date.now()}}catch(e){setError((e as Error).message)}}
 return <View className="media-page"><View className="media-heading"><Text className="media-eyebrow">灵感影像</Text>{id&&detail&&<Text className="media-title">{detail.series.titleZh}</Text>}</View>{error&&<View className="media-notice">{error}<ActionButton  onClick={()=>load()}>重试</ActionButton></View>}{loading&&<LoadingState detail={Boolean(id)} refresh={Boolean(detail||rows.length)}/>}
 {!id?<><View className="media-search"><ActionInput placeholder="搜索视频" value={q} onInput={e=>setQ(e.detail.value)} onConfirm={()=>load('',q,type,1)}/><ActionButton  onClick={()=>load('',q,type,1)}>搜索</ActionButton></View><View className="media-tabs">{[['','全部'],['drama','短剧'],['course','课程'],['other','其他']].map(([key,label])=><ActionText className={type===key?'selected':''} key={key} onClick={()=>{setType(key);void load('',q,key,1)}}>{label}</ActionText>)}</View><View className="media-grid">{rows.map(row=><ActionView disabled={loading} className="media-card"  key={row.id} onClick={()=>!loading&&Taro.navigateTo({url:'/pages/videos/index?id='+row.id})}><View className="media-thumbnail">{row.imageId?<Image src={image(row.imageId)} mode="aspectFill"/>:<Text className="media-placeholder">视频专栏</Text>}</View><Text className="media-card-title">{row.titleZh}</Text><Text className="media-muted">{row.episodes} 集 · {row.finished?'已完结':'更新中'}</Text></ActionView>)}</View>{!loading&&!rows.length&&<View className="media-empty">暂无视频内容</View>}<View className="media-pages"><ActionButton  disabled={loading||page<=1} onClick={()=>load('',q,type,page-1)}>上一页</ActionButton><Text>{page} / {pages}</Text><ActionButton  disabled={loading||page>=pages} onClick={()=>load('',q,type,page+1)}>下一页</ActionButton></View></>:detail&&<>
 {play?<Video id="series-player" src={origin+api+'stream&ticket='+encodeURIComponent(play.ticket)+'&file=index.m3u8'} initialTime={play.position} autoplay controls onFullscreenChange={e=>setFull(Boolean(e.detail.fullScreen))} onTimeUpdate={e=>{if(Taro.getStorageSync(choiceKey)==='accepted')metrics.current.tick(e.detail.currentTime,e.detail.duration,Date.now(),true).forEach((event:string)=>behavior(event,episode.id));void progress(e.detail.currentTime)}} onPause={()=>metrics.current.tick(0,0,Date.now(),false)} onEnded={()=>void progress(episode.duration,true)} onError={()=>setError('视频播放失败，请重新选择本集；也请检查视频下载域名配置')}/>:detail.series.imageId&&<Image className="media-cover" src={image(detail.series.imageId)} mode="aspectFit"/>}<Text className="media-description">{detail.series.summaryZh}</Text><RichBody nodes={detail.series.nodes||[]} onFullscreen={setFull}/><View className="media-section-title">选集 · {detail.episodes.length} 集</View><View className="media-episodes">{detail.episodes.map((ep:any,index:number)=><ActionButton  className={episode?.id===ep.id?'selected':''} key={ep.id} onClick={()=>start(ep)}>{index+1}. {ep.titleZh} {ep.preview?'· 公开试看':''}</ActionButton>)}</View>{!detail.episodes.length&&<Text>暂无可播放剧集</Text>}{episode&&<MediaInteractions kind="videos" id={episode.id} parentId={id}/>}</>}
 <GlobalNavigation active="videos" hidden={full}/></View>
}
