import {ActionButton,ActionView,ActionInput,ActionTextarea} from '../../components/interaction';
import LoadingState from '../../components/loading-state';
import {latestRequest} from '../../lib/latest-request.mjs';
import {useRef,useState} from 'react';
import Taro,{useLoad,useUnload,useDidShow,useShareAppMessage,useShareTimeline} from '@tarojs/taro';
import {View,Text,Image,Input,Textarea,Button,Checkbox,CheckboxGroup,Picker} from '@tarojs/components';
import {request,image,token,upload} from '../../lib/api';
import {publicationLabel} from '../../../../lib/mini-content.mjs';
import GlobalNavigation from '../../components/global-navigation';
import RichBody from '../../components/rich-body';
import MediaInteractions from '../../components/media-interactions';
import { publicMediaShare } from '../../lib/share.mjs';
import '../videos/index.scss';
const api='/api/mini/media?kind=salons&action=';
const phases:Record<string,string>={registering:'报名中',upcoming:'即将开放',registrationClosed:'报名已截止',ongoing:'进行中',ended:'已结束',closed:'已关闭',cancelled:'已取消',published:'已发布'};
export default function Salons(){
 const loads=useRef(latestRequest());useUnload(()=>loads.current.cancel());
 const [id,setId]=useState(''),[event,setEvent]=useState<any>(),[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(1),[registration,setRegistration]=useState<any>(),[answers,setAnswers]=useState<Record<string,string>>({}),[consent,setConsent]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[full,setFull]=useState(false),[form,setForm]=useState(false);
 const pending=useRef(false),lock=useRef(false),currentId=useRef(''),actor=useRef(token());
 useLoad(params=>{const value=params.id||'';currentId.current=value;setId(value);void load(value)});
 useDidShow(()=>{if(actor.current!==token()){actor.current=token();setRegistration(undefined);setAnswers({});setConsent(false);setForm(false);setError('');lock.current=false;setBusy(false);}if(currentId.current&&token())void refresh(currentId.current);if(pending.current&&token()){pending.current=false;setForm(true)}});
 useShareAppMessage(()=>publicMediaShare('salons',{id,titleZh:event?.titleZh},'沙龙会'));
 useShareTimeline(()=>publicMediaShare('salons',{id,titleZh:event?.titleZh},'沙龙会'));
 async function refresh(value=id){const session=token();try{const result=await request(api+'registration&id='+value,undefined,session);if(token()===session)setRegistration(result.registration)}catch(e){if(token()===session)setError((e as Error).message)}}
 async function load(value=id,n=page){const version=loads.current.begin();setError('');setLoading(true);try{const result=await request(api+(value?'detail&id='+value:'list&q='+encodeURIComponent(q)+'&page='+n));if(!loads.current.isCurrent(version))return;if(value){setEvent(result.event);if(token())await refresh(value)}else{setRows(result.rows);setPages(result.pages||1);setPage(result.page||n)}}catch(e){if(loads.current.isCurrent(version))setError((e as Error).message)}finally{if(loads.current.isCurrent(version))setLoading(false)}}
 async function register(){if(!token()){pending.current=true;await Taro.navigateTo({url:'/pages/login/index'});return;}setForm(true)}
 async function mutate(action:string,extra:any={}){if(lock.current)return;const session=token();if(!session||session!==actor.current){setError('账号已变更，请重新填写报名信息');return;}lock.current=true;setBusy(true);setError('');try{const result=await request(api+action,{id,...extra},session);if(token()!==session)return;setRegistration(result.registration);setForm(false);await load();void Taro.showToast({title:action==='register'?'报名成功':action==='checkin'?'签到成功':'已取消报名',icon:'success'})}catch(e){if(token()===session)setError((e as Error).message)}finally{if(token()===session){lock.current=false;setBusy(false)}}}
 async function checkin(){try{const scanned=await Taro.scanCode({onlyFromCamera:true,scanType:['qrCode']});const raw=scanned.result;const code=raw.match(/[?&]code=([^&#]+)/)?.[1]||raw;await mutate('checkin',{code:decodeURIComponent(code)})}catch(e){if(!String((e as any).errMsg||'').includes('cancel'))setError((e as Error).message||'无法读取签到码')}}
 async function cancel(){if((await Taro.showModal({title:'取消报名',content:'确认取消本次活动报名？'})).confirm)await mutate('cancel')}
 const field=(key:string,value:string)=>setAnswers(old=>({...old,[key]:value}));
 return <View className="media-page"><View className="media-heading"><Text className="media-eyebrow">相聚与交流</Text>{id&&event&&<Text className="media-title">{event.titleZh}</Text>}</View>{error&&<View className="media-notice">{error}<ActionButton  onClick={()=>load()}>重试</ActionButton></View>}{loading&&<LoadingState detail={Boolean(id)} refresh={Boolean(event||rows.length)}/>}
 {!id?<><View className="media-search"><ActionInput value={q} placeholder="搜索沙龙会" onInput={e=>setQ(e.detail.value)} onConfirm={()=>load('',1)}/><ActionButton  onClick={()=>load('',1)}>搜索</ActionButton></View><View className="salon-list">{rows.map(row=><ActionView disabled={loading} className="media-card"  key={row.id} onClick={()=>!loading&&Taro.navigateTo({url:'/pages/salons/index?id='+row.id})}><View className="media-thumbnail">{row.imageId?<Image src={image(row.imageId,'card')} mode="aspectFill" lazyLoad/>:<Text className="media-placeholder">沙龙会</Text>}</View><View className="media-card-info"><Text className="media-card-title">{row.titleZh}</Text><Text className="media-muted">{publicationLabel(row.starts)}</Text><Text className="media-muted">{row.locationZh}</Text><Text className="salon-badge">{phases[row.phase]||phases[row.status]||''}</Text></View></ActionView>)}</View>{!loading&&!rows.length&&<View className="media-empty">暂无沙龙会，敬请期待</View>}<View className="media-pages"><ActionButton  disabled={loading||page<=1} onClick={()=>load('',page-1)}>上一页</ActionButton><Text>{page} / {pages}</Text><ActionButton  disabled={loading||page>=pages} onClick={()=>load('',page+1)}>下一页</ActionButton></View></>:event&&<>{event.imageId&&<Image className="media-cover" src={image(event.imageId,'hero')} mode="aspectFit" lazyLoad/>}<View className="salon-hero-meta"><Text className="salon-badge">{phases[event.phase]||'活动详情'}</Text><Text className="salon-detail-title">{event.titleZh}</Text></View><View className="salon-facts salon-detail-facts"><View><Text>活动时间</Text><Text>{publicationLabel(event.starts)} — {publicationLabel(event.ends)}</Text></View><View><Text>活动地点</Text><Text>{event.locationZh} {event.addressZh}</Text></View>{event.organizer&&<View><Text>主办方</Text><Text>{event.organizer}</Text></View>}<View><Text>报名名额</Text><Text>{event.remaining===null?'名额不限':'剩余 '+event.remaining+' 个名额'}</Text></View></View><Text className="media-description">{event.summaryZh}</Text><RichBody nodes={event.nodes||[]} onFullscreen={setFull}/>
 {registration&&<View className="salon-facts"><Text className="media-card-title">我的报名</Text><Text>{registration.status==='active'?(registration.checkedAt?'已签到':'报名成功，待签到'):'报名已取消'}</Text><Text>报名时间：{publicationLabel(registration.created)}</Text>{registration.checkedAt&&<Text>签到时间：{publicationLabel(registration.checkedAt)}</Text>}{registration.status==='active'&&!registration.checkedAt&&<><ActionButton  disabled={busy} onClick={checkin}>扫描现场二维码签到</ActionButton>{event.allowCancel&&<ActionButton  disabled={busy} onClick={cancel}>取消报名</ActionButton>}</>}</View>}
 {(!registration||registration.status!=='active')&&<ActionButton  className="media-primary" disabled={event.phase!=='registering'||event.remaining===0} onClick={register}>{event.phase==='registering'?(event.remaining===0?'名额已满':'立即报名'):(phases[event.phase]||'暂不可报名')}</ActionButton>}
 {form&&<View className="salon-form"><Text className="media-card-title">填写报名信息</Text>{event.fields.map((f:any)=><View key={f.id} className="salon-field"><Text>{f.labelZh}{f.required?' *':''}</Text>{f.type==='textarea'?<ActionTextarea value={answers[f.id]||''} onInput={e=>field(f.id,e.detail.value)}/>:f.type==='image'?<ActionButton  onClick={async()=>{const session=token();if(session!==actor.current)return;try{const result=await upload(api+'upload',{eventId:id,fieldId:f.id});if(token()===session)field(f.id,'/api/submission-file/'+result.id)}catch(e){setError((e as Error).message)}}}>{answers[f.id]?'已上传，点击更换':'上传图片'}</ActionButton>:['date','time'].includes(f.type)?<Picker mode={f.type} value={answers[f.id]} onChange={(e:any)=>field(f.id,String(e.detail.value))}><ActionView className="salon-picker">{answers[f.id]||'请选择'}</ActionView></Picker>:<ActionInput type={f.type==='number'?'digit':f.type==='phone'?'number':'text'} value={answers[f.id]||''} onInput={e=>field(f.id,e.detail.value)}/>}</View>)}<CheckboxGroup onChange={e=>setConsent(e.detail.value.includes('yes'))}><Checkbox value="yes" checked={consent}/>我同意提交以上信息用于本次活动报名及联系。</CheckboxGroup><ActionButton  className="media-primary" loading={busy} disabled={busy||!consent} onClick={()=>mutate('register',{answers,consent})}>提交报名</ActionButton><ActionButton  disabled={busy} onClick={()=>setForm(false)}>收起</ActionButton></View>}
 <MediaInteractions kind="salons" id={id}/></>}
 <GlobalNavigation active="events" hidden={full}/></View>
}
