# Generated by Django 5.2.17 on 2026-09-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='password_stamp',
            field=models.CharField(default='', max_length=64),
        ),
    ]
