# Generated by Django 5.2.17 on 2026-09-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_session_password_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='password_stamp',
            field=models.CharField(default='', max_length=64),
        ),
    ]
