# Generated by Django 5.2.17 on 2026-09-08 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_visitorstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxFlow',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('browser', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=20)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialConfig',
            fields=[
                ('provider', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('sort', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='visitorstate',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visitorstate',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='visitorstate',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='visitorstate',
            name='last_login_method',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='visitorstate',
            name='registration_source',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='visitorstate',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='social_provider_subject')],
            },
        ),
    ]
