# Generated by Django 5.2.17 on 2026-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sandboxflow_socialconfig_visitorstate_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxflow',
            name='binding_session',
            field=models.CharField(default='', max_length=64),
        ),
    ]
