# Generated by Django 5.2.17 on 2026-09-08 10:05

from django.db import migrations


def classify(apps,schema_editor):
    import hashlib
    User=apps.get_model('auth','User');State=apps.get_model('accounts','VisitorState')
    for user in User.objects.filter(is_staff=False,is_superuser=False).iterator():
        state,_=State.objects.get_or_create(user_id=user.pk)
        if state.registration_source=='unknown' and user.username==hashlib.sha256(user.email.lower().encode()).hexdigest():
            state.registration_source='email';state.save(update_fields=['registration_source'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sandboxflow_binding_session'),
    ]

    operations = [migrations.RunPython(classify,migrations.RunPython.noop)]
