# Generated by Django 5.2.17 on 2026-09-08 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_classify_existing_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='socialidentity',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='social_user_provider'),
        ),
    ]
