# Generated by Django 5.2.17 on 2026-09-08 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_socialidentity_social_user_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonEvent',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('data', models.JSONField(default=dict)),
                ('checkin_code', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalonRegistration',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('fields', models.JSONField(default=list)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=16)),
                ('checked_at', models.DateTimeField(null=True)),
                ('checkin_method', models.CharField(default='', max_length=16)),
                ('checkin_actor', models.CharField(default='', max_length=254)),
                ('note', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='accounts.salonevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalonMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.salonregistration')),
            ],
        ),
        migrations.CreateModel(
            name='SalonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=254)),
                ('action', models.CharField(max_length=40)),
                ('reason', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.salonevent')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.salonregistration')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salonregistration',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='salon_event_user'),
        ),
    ]
