# Generated by Django 5.2.17 on 2026-09-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_salonevent_salonregistration_salonmail_salonlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingGrant',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('permissions', models.JSONField(default=list)),
            ],
        ),
    ]
