# Generated by Django 5.2.17 on 2026-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_marketinggrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmail',
            name='claimed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
