# Generated by Django 5.2.17 on 2026-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_salonmail_claimed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonlog',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
