# Generated by Django 5.2.17 on 2026-09-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_salonlog_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(default='editor', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('must_change', models.BooleanField(default=True)),
                ('bootstrap', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password_stamp', models.CharField(max_length=64)),
                ('expires', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffaccount')),
            ],
        ),
    ]
