# Generated by Django 5.2.17 on 2026-09-09 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_staffaccount_staffsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('version', models.CharField(default='', max_length=64)),
                ('duration', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('error', models.CharField(default='', max_length=250)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.videoepisode')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlayback',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('viewer', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('expires', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.videoepisode')),
            ],
        ),
        migrations.AddField(
            model_name='videoepisode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.videoseries'),
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer', models.CharField(max_length=64)),
                ('position', models.FloatField(default=0)),
                ('seconds', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.videoepisode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('episode', 'viewer'), name='video_viewer_episode')],
            },
        ),
    ]
