# Generated by Django 5.2.17 on 2026-09-09 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_videoepisode_videosecuritylog_videoseries_videojob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('size', models.BigIntegerField()),
                ('received', models.BigIntegerField(default=0)),
                ('folder', models.CharField(default='', max_length=80)),
                ('status', models.CharField(default='uploading', max_length=16)),
                ('owner', models.CharField(default='', max_length=80)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
