# Generated by Django 5.2.17 on 2026-09-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_pointrule_pointaccount_pointentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('target', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('path', models.CharField(default='', max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'target', 'action'), name='content_interaction_unique')],
            },
        ),
    ]
