# Generated by Django 5.2.17 on 2026-09-09 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_contentinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrule',
            name='enabled_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
