# Generated by Django 5.2.17 on 2026-09-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_pointrule_enabled_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRuleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
                ('effective_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'effective_at'], name='accounts_po_key_e844be_idx')],
            },
        ),
    ]
