# Generated by Django 5.2.17 on 2026-09-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_pointrulerevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthFlow',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('browser', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=20)),
                ('verifier', models.CharField(max_length=128)),
                ('terms', models.IntegerField()),
                ('privacy', models.IntegerField()),
                ('lang', models.CharField(default='zh', max_length=2)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='socialconfig',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='socialconfig',
            name='real_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialconfig',
            name='secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
