# Generated by Django 5.2.17 on 2026-09-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_oauthflow_socialconfig_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthflow',
            name='binding_session',
            field=models.CharField(default='', max_length=64),
        ),
    ]
