# Generated by Django 5.2.17 on 2026-09-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_oauthflow_binding_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthflow',
            name='return_to',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
