# Generated by Django 5.2.17 on 2026-09-14 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_oauthflow_return_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=254)),
                ('action', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=254)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('permissions', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPermissionAssignment',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.staffaccount')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(to='accounts.permissiongroup')),
            ],
        ),
    ]
