# Generated by Django 5.2.17 on 2026-09-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_permission_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='target',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
