# Generated by Django 5.2.17 on 2026-09-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_audit_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='target',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
    ]
